CREATE TYPE chat_status AS ENUM ('UNSERVED', 'SERVED');

CREATE TABLE chat (
    id SERIAL PRIMARY KEY,
    room_id VARCHAR NOT NULL,
    status chat_status NOT NULL DEFAULT 'UNSERVED',
    data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);